# Generated by Django 3.2 on 2021-04-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=100)),
                ('buildorder', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
