# Generated by Django 3.2 on 2021-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_buildorders_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildorders',
            name='age',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildorders',
            name='explanation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildorders',
            name='headline',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='buildorders',
            name='writer',
            field=models.CharField(max_length=30),
        ),
    ]
