# Generated by Django 3.2 on 2021-04-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_auto_20210423_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('voted', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='buildorders',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
