# Generated by Django 3.2 on 2021-04-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20210424_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='user',
            new_name='user1',
        ),
    ]
