# Generated by Django 3.2 on 2021-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_auto_20210425_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildorders',
            name='approved',
            field=models.BooleanField(default='False', verbose_name='Onaylanma'),
        ),
        migrations.AddField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default='False'),
        ),
    ]
