# Generated by Django 3.2 on 2021-04-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_auto_20210425_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildorders',
            name='build_list',
            field=models.CharField(default=0, max_length=1000, verbose_name='Liste Şeklinde'),
            preserve_default=False,
        ),
    ]
