# Generated by Django 3.2 on 2021-04-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0012_auto_20210425_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='combuildtitle',
        ),
    ]
